### PR TITLE
Fixed Bug 19

### PR DESCRIPTION
**Pull request by jrovegno**
@csvy/team This is an attempt to close the problem posed in #19 .

### CODE REVIEW

**Comment by jrovegno** [comment]
@jcolomb @CharlesNepote Any thoughts? @csvy/team with this PR I think we can release the first stable version of the spec, If someone have an objection this is good time to do the changes.

**Comment by leeper** [comment]
I'm happy with this.

**Comment by CharlesNepote** [comment]
Well done. Two small point by the way.

I was asking myself about the "mediatype" property: the documentation provide "text/vnd.yaml". Isn't it redundant as every property of a CSVY file has to be a YAML file?

Also, nothing is said about the file extension for a CSVY file when it is located on a filesystem: should it be always mydata.csvy? mydata.csv? mydata.yml? I think we should precise this.

**Comment by jrovegno** [comment]
@CharlesNepote [mediatype and other metadata properties are optional](http://frictionlessdata.io/specs/data-resource/).

The file extension, at the moment,  there are 3 options:

- csvy: metadata+data in one file
- csv: metadata in the comments, Backward compatibility
- mydata.csv + mydata.yml : discourage this option, should we eliminate this option?

**Pull request merged**
